spring:
  application:
    name: eureka
 
server:
  port: 8761
 
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/